// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HomeView() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Home</h1><div class=\"row\"><div class=\"col-md-1 ms-auto\"><div><button hx-get=\"/login\" hx-trigger=\"click\" hx-target=\"#todo-list-body\">Login</button></div></div></div><div><h2>To-Do List</h2><form hx-post=\"/tasks\" hx-trigger=\"submit\" hx-target=\"#task-list\" hx-swap=\"innerHTML\"><input type=\"text\" name=\"description\" placeholder=\"New Task\" required> <button type=\"submit\">Add Task</button></form><div class=\"button-container\" hx-target=\"#task-list\"><button hx-get=\"/tasks\">Filter All Tasks</button> <button hx-get=\"/completed\">Filter Completed Tasks</button> <button hx-get=\"/incomplete\">Filter Incomplete Tasks</button></div><div class=\"list-container px-3 mx-3\" id=\"task-list\" hx-get=\"/tasks\" hx-trigger=\"load\" hx-swap=\"innerHTML\"><!-- Tasks will be dynamically loaded here --></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
