// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func HomeView() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1>Home</h1><div class=\"row\"><div class=\"col-md-1 ms-auto\"><div><button hx-get=\"/login\" hx-trigger=\"click\" hx-target=\"#todo-list-body\">Login</button></div></div></div><div><h2>To-Do List</h2><form hx-post=\"/tasks\" hx-trigger=\"submit\" hx-target=\"#task-list\" hx-swap=\"innerHTML\"><input type=\"text\" name=\"description\" placeholder=\"New Task\" required> <button type=\"submit\">Add Task</button></form><div class=\"button-container\" hx-target=\"#task-list\"><button hx-get=\"/tasks\">Filter All Tasks</button> <button hx-get=\"/completed\">Filter Completed Tasks</button> <button hx-get=\"/incomplete\">Filter Incomplete Tasks</button></div><div class=\"list-container px-3 mx-3\" id=\"task-list\" hx-get=\"/tasks\" hx-trigger=\"load\" hx-swap=\"innerHTML\"><!-- Tasks will be dynamically loaded here --></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
