// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package storedb

import (
	"database/sql"
)

type Task struct {
	ID          int32
	Description sql.NullString
	Completed   sql.NullBool
	Addedfrom   sql.NullString
}
