# .air.toml

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "tmp/main"
full_bin = "tmp/main"
exclude_dir = ["tmp"]
include_ext = ["go", "tmpl", "html"]

[log]
level = "info"

# Enable live-reloading on the browser.
[proxy]
  enabled = true
  proxy_port = 8090
  app_port = 5000 
