name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli
          aws --version

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install EB CLI
        run: |
          pip install awsebcli
          python -m venv ~/.ebcli-virtual-env
          source ~/.ebcli-virtual-env/bin/activate
          pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set up environment 
        run: |
          touch .env
          echo ELASTIC_BEANSTALK_ENVIRONMENT_DOMAIN=${{ secrets.ELASTIC_BEANSTALK_ENVIRONMENT_DOMAIN }} >> .env

      - name: Run build and deployment script
        run: |
          chmod +x recursiveBuild.sh
          ./recursiveBuild.sh
